apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-html
  namespace: dev
data:
  index.html: |
    <html>
    <body>
      <h1>Hello Francisco! Kubernetes Ingress is working!</h1>
    </body>
    </html>

