apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-html
  namespace: dev
data:
  index.html: |
    <html>
    <body>
      <h1>Hello Francisco! Kubernetes is working!</h1>
      <p>Frontend talking to backend at <a href="/backend">backend</a></p>
    </body>
    </html>
